<?php

namespace HunterBundle\Repository;

/**
 * ListProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListProductRepository extends \Doctrine\ORM\EntityRepository
{
}
