<?php

namespace HunterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoreProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreProductRepository extends EntityRepository
{
}
